// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1snEfl5Kz7qPpk0dMhjEFQaummfPpIzs',
    appId: '1:287947960224:web:3b76c815e700e3212cbec5',
    messagingSenderId: '287947960224',
    projectId: 'ltdnt-d731b',
    authDomain: 'ltdnt-d731b.firebaseapp.com',
    storageBucket: 'ltdnt-d731b.firebasestorage.app',
    measurementId: 'G-MZ8R18JK9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMJY7O9rfnApT9f_t2JRB9sfFw7obZTcM',
    appId: '1:287947960224:android:b1fb795fa8c81d062cbec5',
    messagingSenderId: '287947960224',
    projectId: 'ltdnt-d731b',
    storageBucket: 'ltdnt-d731b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSavmyOH8XzaRRlyqsJgyB4bPeV_eqySM',
    appId: '1:287947960224:ios:8e9bb8747168e74c2cbec5',
    messagingSenderId: '287947960224',
    projectId: 'ltdnt-d731b',
    storageBucket: 'ltdnt-d731b.firebasestorage.app',
    iosBundleId: 'com.example.caohoanganhvu2324802010159Lab4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSavmyOH8XzaRRlyqsJgyB4bPeV_eqySM',
    appId: '1:287947960224:ios:8e9bb8747168e74c2cbec5',
    messagingSenderId: '287947960224',
    projectId: 'ltdnt-d731b',
    storageBucket: 'ltdnt-d731b.firebasestorage.app',
    iosBundleId: 'com.example.caohoanganhvu2324802010159Lab4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1snEfl5Kz7qPpk0dMhjEFQaummfPpIzs',
    appId: '1:287947960224:web:d3409a5819c9d2452cbec5',
    messagingSenderId: '287947960224',
    projectId: 'ltdnt-d731b',
    authDomain: 'ltdnt-d731b.firebaseapp.com',
    storageBucket: 'ltdnt-d731b.firebasestorage.app',
    measurementId: 'G-8V1TRH1RP7',
  );

}